### Importando librerias

In [ ]:
import numpy as np

In [ ]:
arr = np.array([1,2,3,4])
arr.dtype

dtype('int64')

numpy trabaja distintos tipos de datos. 
el tipo de dato que muestra: enteros de 64 bits

In [ ]:
arr = np.array([1,2,3,4], dtype='float64')
arr.dtype

dtype('float64')

qué pasa si no queremos ese tipo de datos, sino float, entonces fuerzo a que adquiera ese tipo de dato, de tipo flotante, todo trabanjo con tensorflow, redes neuronales usa ese tipo de dato

In [ ]:
arr

array([1, 2, 3, 4])

### Cambiando tipo de datos

In [ ]:
arr = np.array([0,1,2,3,4])
arr = arr.astype(np.bool_)
arr

array([False,  True,  True,  True,  True])

In [ ]:
arr = np.array([0,1,2,3,4])
arr = arr.astype(np.string_)
arr

array([b'0', b'1', b'2', b'3', b'4'], dtype='|S21')

aquí, definí el tipo de dato, directamente desde la librería de numpy, le coloca esa b delante porque al ser un número me indica que el tipo es string

In [ ]:
arr = np.array(['0','1','2','3','4'])
arr = arr.astype(np.int8)
arr

array([0, 1, 2, 3, 4], dtype=int8)

Aquí, estoy haciendo al revés, ya que pongo los número como enteros y luego le digo que le tipo de datos es entero y funciona

In [ ]:
arr = np.array(['hola','1','2','3','4'])
arr = arr.astype(np.int8)
arr

ValueError: ignored

Aquí me arroja un error, porque no puedo mezclar los tipos de datos. 

Lista de tipo de datos en numpy:
https://numpy.org/doc/stable/user/basics.types.html

Recordar que el array, puede tener un único tipo de dato, esto podría producir perdida de toda optimización al ser almacenado en memoria. 


1.   Un único tipo de dato voy a trabajar con el array
2.   Un único tipo de dato voy a definir para trabajar

