### Importar librerías

Dos funciones importantes de los arreglos: 
- Shape: me indica la forma que tiene un arreglo, qué estructura estoy trabajando, cómo se está comportando, cómo puedo ingresar a él, como manipularlo.


In [2]:
import numpy as np 

In [3]:
arr = np.random.randint(1,10,(3,2))

generamos un array aleatorios de 1 a 10, con una estructura de 3 x 2. Lo guardamos dentro de un array

### Shape

In [ ]:
arr.shape

(3, 2)

aquí me devuelve, cuántas filas y cuántas columnas tengo

In [ ]:
arr

array([[9, 6],
       [8, 9],
       [4, 2]])

### Reshape

In [ ]:
arr.reshape(1,6)

array([[9, 6, 8, 9, 4, 2]])

reshape, cambia la forma como estuvo antes. en el ejemplo arr era de 3x2 con el reshape pasa a 1x6

In [ ]:
arr.reshape(2,3)

array([[9, 6, 8],
       [9, 4, 2]])

In [ ]:
np.reshape(arr,(1,6))

array([[9, 6, 8, 9, 4, 2]])

In [ ]:
arr

array([[9, 6],
       [8, 9],
       [4, 2]])

In [ ]:
np.reshape(arr,(2,3),'C')

array([[9, 6, 8],
       [9, 4, 2]])

le voy a hacer un reshape de una estructura de 2 x 3 en el lenguaje C, lo ordena por filas

In [ ]:
np.reshape(arr,(2,3),'F')

array([[9, 4, 9],
       [8, 6, 2]])

Aquí lo ordena distinto, aquí con F, lo hace como fortran, lo ordena por columna

In [ ]:
np.reshape(arr,(2,3),'A')

array([[9, 6, 8],
       [9, 4, 2]])

Aquí lo ordena según como está optimizado el guardado de datos en memoría en mi laptop

https://numpy.org/doc/stable/reference/generated/numpy.ndarray.shape.html