### Importando librerías

In [ ]:
import numpy as np

In [ ]:
arr = np.random.randint(1,100,(3,10))

In [ ]:
arr

array([[ 9, 18, 82, 55, 15, 95,  7, 36, 81, 57],
       [38, 16, 39, 90, 20,  7, 61, 41, 46, 75],
       [50, 92, 31, 37, 88, 28, 62, 48, 74, 33]])

In [ ]:
matriz = arr.reshape(6,5)


In [ ]:
matriz

array([[ 9, 18, 82, 55, 15],
       [95,  7, 36, 81, 57],
       [38, 16, 39, 90, 20],
       [ 7, 61, 41, 46, 75],
       [50, 92, 31, 37, 88],
       [28, 62, 48, 74, 33]])

Lo llevamos a una estructura matricial 

In [ ]:
arr = np.random.randint(1,20,10)

In [ ]:
arr

array([12,  2, 16, 16, 17,  1, 13, 14,  6,  3])

### Max

In [ ]:
arr

array([[ 9, 18, 82, 55, 15, 95,  7, 36, 81, 57],
       [38, 16, 39, 90, 20,  7, 61, 41, 46, 75],
       [50, 92, 31, 37, 88, 28, 62, 48, 74, 33]])

In [ ]:
arr.max()

95

Me devuelve el máximo valor 

In [ ]:
matriz

array([[12,  2, 16, 16, 17],
       [ 1, 13, 14,  6,  3]])

In [ ]:
matriz

array([[ 9, 18, 82, 55, 15],
       [95,  7, 36, 81, 57],
       [38, 16, 39, 90, 20],
       [ 7, 61, 41, 46, 75],
       [50, 92, 31, 37, 88],
       [28, 62, 48, 74, 33]])

In [ ]:
matriz.max( )

95

matriz.max(0) aquí le indico que me diga cuál es el máximo por columna

In [ ]:
matriz.max(1)

array([17, 14])

el máximo valor por fila

### Argmax

In [ ]:
arr.argmax()

0

me devuelve un 0 porque es el índice del valor más grande de nuestro array, si hay varios, devuelve el menor índice

In [ ]:
matriz.argmax(0)

array([0, 1, 1, 0, 0])

### Min

In [ ]:
arr.min()

9

In [ ]:
matriz.min(0)

array([18,  9, 15, 12, 14])

En el caso de la matríz, si pongo 0 lo hace por el eje y

### Argmin

In [ ]:
arr

array([12,  2, 16, 16, 17,  1, 13, 14,  6,  3])

In [ ]:
arr.argmin()

1

Me devuelve el índice del valor más pequeño que tengo en mi array

In [ ]:
matriz

array([[ 9, 18, 82, 55, 15],
       [95,  7, 36, 81, 57],
       [38, 16, 39, 90, 20],
       [ 7, 61, 41, 46, 75],
       [50, 92, 31, 37, 88],
       [28, 62, 48, 74, 33]])

In [ ]:
matriz.argmax(1)

array([2, 0, 3, 4, 1, 3])

In [ ]:
matriz

array([[12,  2, 16, 16, 17],
       [ 1, 13, 14,  6,  3]])

In [ ]:
matriz.argmin(1)

array([1, 3])

Me devuelve, el índice del valor más pequeño en el eje x (filas)

### Ptp

pick to pick (de un pico a otro pico)

In [ ]:
arr

array([[ 9, 18, 82, 55, 15, 95,  7, 36, 81, 57],
       [38, 16, 39, 90, 20,  7, 61, 41, 46, 75],
       [50, 92, 31, 37, 88, 28, 62, 48, 74, 33]])

In [ ]:
arr.ptp(1)

array([88, 83, 64])

el valor más pequeño es: 1, el valor más alto es: 17 la diferencia (de un pico a otro) es 16

In [ ]:
matriz

array([[12,  2, 16, 16, 17],
       [ 1, 13, 14,  6,  3]])

In [ ]:
matriz.ptp(0)

array([11, 11,  2, 10, 14])

en el caso de la matríz, hace la diferencia del pico más bajo con el pico más alto por el eje y (en cada columna)

### Concatenate

In [ ]:
a = np.array([[1,2],[3,4]])
b = np.array([5,6])


creamos dos arrays: a de 2 x 2, b 

In [ ]:
np.concatenate((a,b),axis=0)

ValueError: ignored

el error que me da es debido a que las dimensiones son distintas y por ello no podré concatenar

In [ ]:
a.ndim


2

con ndim veo la dimensión que tienen el array a, me sale 2

In [ ]:
b.ndim

1

por el contrario, el array b me sale 1. 

Es por ello que no puedo concatenar, ambos arrays deben de tener la misma dimensión para ello usamos expand. 

In [ ]:
b = np.expand_dims(b,axis=0)

expando la dimensión del array b, por el eje 0 y lo volvemos a guardar en b para que se actualice

In [ ]:
np.concatenate((a,b),axis=0)

array([[1, 2],
       [3, 4],
       [5, 6]])

Vuelvo a utilizar la instrucción concatenar (por el eje 0) y comprobamos que concateno ambos arrays

In [ ]:
b

array([[5, 6]])

In [ ]:
np.concatenate((a,b),axis=1)

ValueError: ignored

que pasa si, por el contrario, quiero concatenar por eje 1, me da error 

In [ ]:
np.concatenate((a,b.T),axis=1)

array([[1, 2, 5],
       [3, 4, 6]])

para salvar el error, utilizamos la traspuesta (T) 
La traspuesta de una matríz 

### Transpuesta

In [ ]:
b.T

array([[5],
       [6]])

Aplicamos la traspuesta de una matríz, en este caso la matríz b.
Por ejemplo si tenemos una matríz 3 x 2, al aplicar la traspuesta (T) da como resultado 2 x 3

In [ ]:
a

array([[1, 2],
       [3, 4]])

In [ ]:
a.T

array([[1, 3],
       [2, 4]])