### Importar librería

In [1]:
import numpy as np

In [ ]:
# Recuperar el arreglo anterior
arr = np.arange(0,11)

# Resultado
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

creamos un array de 0 a 11 (no toma el 11)

In [ ]:
# Troceado de arreglos
trozo_de_arr = arr[0:6]

operamos un slicing  de 0 a 5 y lo guardo en una variable trozo_de_arr

In [ ]:
# Cambios 
trozo_de_arr[:] = 0

# Mostrar slice nuevamete
trozo_de_arr

array([0, 0, 0, 0, 0, 0])

A todo mi arreglo trozo_de_arr le asigno el valor 0.
Quiere decir, que los nuevos valores ahora tendrán 0 perdiendo los valores anteriors

In [ ]:
arr

array([ 0,  0,  0,  0,  0,  0,  6,  7,  8,  9, 10])

cuando compruebo que mi arreglo arr ha sido afectado por el cambio que hice a arreglo trozo_de_arr con este cambio, si vemos las posiciones de 0 a 5 están con el valor 0, esto es un error que debo de corregir.
Esto sucede en muchas estructuras de python que cuando quiero realizar algunos cambios en una parte, sigo haciendo referencia al objeto padre en memoria y es lo que no quería. Aquí es donde aparece el comando copy

In [ ]:
# Para obtener una copia es necesario usar el método copy()
arr_copy = arr.copy()

con esta asignación, puedo realizar los cambios que desee en una parte de un arreglo sin afectar el arreglo padre. 

In [ ]:
arr_copy[:] = 100

por ejemplo, a todo el arreglo denominado arr_copy le asigno el valor 100

In [ ]:
arr_copy

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100])

Vemos que todo el arreglo arr_copy está asignado con el valor 100

In [ ]:
arr

array([ 0,  0,  0,  0,  0,  0,  6,  7,  8,  9, 10])

comprobamos que el arreglo padre arr no se ve afectado con el cambio (asignación de 100) por que con la instrucción copy, le he pedido que realice los cambios en otra porción de memoria, son dos objetos totalmente distintos

https://numpy.org/doc/stable/reference/generated/numpy.copy.html