### Importar librería

In [1]:
import numpy as np 

In [2]:
arr = np.linspace(1,10,10, dtype='int8')
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10], dtype=int8)

creamos un array, de número inferior: 1, número superior: 10, 10 elementos. Que me retorne de tipo entero 8 y lo guardamos en un array denominado arr

In [3]:
#Validación elemento a elemento
indices_cond = arr > 5 
indices_cond

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

En este caso le hago la consulta: cuáles valores son mayores a 5 y el resultado que me asigne a indices_cond.
Cuando ejecuto indices_cond. compruebo que cada valor (10 en total) me da resultado booleano, False cuando el valor es menor a 5 y True cuando lo es. 

In [ ]:
# Seleccion de elementos basados en alguna condición
arr[indices_cond]

array([ 6,  7,  8,  9, 10], dtype=int8)

En este caso, en vez de querer que me devuelva una lista con resultados booleanos, yo quiero que me devuelva los valores que cumplan la condición que les planteé, en este caso indices_cond > 5, para ello, en el arreglo arr le coloco dentro de la posición (por ello lo pongo entre los corchetes []) 

In [ ]:
arr[arr > 5]

array([ 6,  7,  8,  9, 10], dtype=int8)

probando de esta manera, me da como resultado lo mismo.

In [ ]:
#Usando condiciones más complejas
arr[(arr > 5) & (arr<9)]

array([6, 7, 8], dtype=int8)

ahora le digo, que me de aquellos valores a 5 y además menores a 9, para ello uso &

In [ ]:
arr[arr > 5] = 99 

Aquí, le estoy indicando, aquellos valores que sean mayores a 6, le asignas el número 99. 

In [ ]:
arr

array([ 1,  2,  3,  4,  5, 99, 99, 99, 99, 99], dtype=int8)

comprobamos que los valores del arreglo original que eran mayores a 5 se les asigno el 99

In [ ]:
arr[arr==99]

array([99, 99, 99, 99, 99], dtype=int8)

aquí le indico que me muestres únicamente los valores que son iguales a 99