### Importar librerías

In [1]:
import numpy as np

In [3]:
lista = [1,2]
lista

[1, 2]

creamos una lista

In [4]:
lista * 3

[1, 2, 1, 2, 1, 2]

la lista en python no entiende que quiero que cada elemento se multiplique por 2 y quede: [2,4], por el contrario, lo que hace es duplicar la lista 

In [7]:
arr = np.arange(0,10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

aquí lo hacemos directamente de numpy, creamos un array de 0 a 10

In [8]:
arr2 = arr.copy()

In [9]:
arr2

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

aquí realizamos una copia y lo asignamos a arr2

In [ ]:
arr2

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

### Operaciones (aritmética simple al array)

In [ ]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
arr * 3

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27])

como vemos, ahora si cada elemento del arreglo arr se le multiplica por 2 

In [ ]:
arr + 2

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [11]:
1 / arr 

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in true_divide
  """Entry point for launching an IPython kernel.


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111])

me realiza la división sin problemas, pero me advierte que el 1er elemento de mi arreglo es 0 y no se puede realizar una división entre 0

In [ ]:
arr ** 2

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

eleva los valores al cuadrado colocando ** 

In [ ]:
arr ** 3

array([  0,   1,   8,  27,  64, 125, 216, 343, 512, 729])

al cubo

### Operaciones entre arrays

In [ ]:
arr + arr2

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

va a sumar los dos arreglos: arr y arr2 

In [ ]:
arr - arr2

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [ ]:
arr * arr2

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

multiplicación de los dos arreglos 

In [ ]:
matriz = arr.reshape(2,5)
matriz2 = matriz.copy()

En el caso de una matríz. 

In [ ]:
matriz

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [ ]:
matriz + matriz2

array([[ 0,  2,  4,  6,  8],
       [10, 12, 14, 16, 18]])

In [ ]:
matriz - matriz2

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

**multiplicación de dos matrices**

debemos de asegurarnos que se puedan multiplicar

In [ ]:
matriz2.T

array([[0, 5],
       [1, 6],
       [2, 7],
       [3, 8],
       [4, 9]])

en este caso a la matriz2 le aplicamos la traspuesta para que puedan multiplicarse

In [ ]:
np.matmul(matriz,matriz2.T)

array([[ 30,  80],
       [ 80, 255]])

una forma directa, sería aplicar la instrucción matmul de numpy pero no descuidando que la matriz2 se le ponga la traspuesta para que pueda multiplicarse.

In [ ]:
matriz @ matriz2.T

array([[ 30,  80],
       [ 80, 255]])

Otra forma igual, sería con el arroba @ pero también añandiendo la traspuesta a matriz2 para que pueda multiplicarse

https://numpy.org/doc/stable/user/absolute_beginners.html#basic-array-operations